name: Woko
favicon: null
layout_spectrum: 0.50694
typography_spectrum: 0.66037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aed3e5'
    - '#95b3b3'
    - '#5e7f78'
    - '#f3fdfc'
    - '#000100'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
