name: Woko
favicon: null
layout_spectrum: 0.8548659801017493
typography_spectrum: 0.7940501570701599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9bdbe'
    - '#000104'
    - '#ffd9b6'
    - '#7e878c'
    - '#c89d8a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
